# ./docker-compose.yml

version: '3.8'

services:
  db:
    image: mysql
    container_name: container_db
    environment:
      MYSQL_DATABASE: gestao_db
      MYSQL_USER: usuario_db
      MYSQL_PASSWORD: 123457
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./db_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: container_app
    volumes:
      - ./src:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
