# Generated by Django 4.2 on 2024-05-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_candidato_usuario_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=150, unique=True)),
                ('sequencia', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
