# Generated by Django 4.2 on 2024-05-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla_modalidade', models.CharField(max_length=7)),
                ('curso', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('convocado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
