version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: gestao_mercearia_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 123457
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: .
    volumes:
      - SIM:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_mysql:
  SIM: