# ./docker-compose.yml

version: '3'
services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    command: ["http-server", "dist/front-end-angular/browser", "-p", "8080"]

